const TeamDetails = [
  {
    name: "Camisha Shiny V",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/aa.png",
  },
  {
    name: "Gokul",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/2gokul.png",
  },
  {
    name: "Keshnee N",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/3keshnee.png",
  },
  {
    name: "Lindsey R Macedo",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/4lindsey.png",
  },
  {
    name: "Navena M",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/5navena.png",
  },
  {
    name: "Nikita Giridhar",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/6nikita.png",
  },
  {
    name: "S Sakthisree",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/7sakthisree.png",
  },
  {
    name: "Swaathy R",
    vertical: "Ambience and Creativity",
    position: "",
    image_url: "/assets/Team/Ambience/8swaathy.png",
  },
  {
    name: "Jeyam Palaniappan D",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/1jeyam.png",
  },
  {
    name: "T G Ashwin Kumar",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/2tg.png",
  },
  {
    name: "Rhubanraj P",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/3rhuban.jpg",
  },
  {
    name: "Sachitha C",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/4sachitha.png",
  },
  {
    name: "Sashti Amar R A",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/5sashti.png",
  },
  {
    name: "Ashwin V",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/6ashwin.png",
  },
  {
    name: "Pushparaj A",
    vertical: "App and Web Development",
    position: "",
    image_url: "/assets/Team/Web/7pushparaj.png",
  },
  {
    name: "Balapravena A S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Balapravena_22b2.png",
  },
  {
    name: "Ajaykumar S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Ajaykumar_S_22b202.png",
  },
  {
    name: "Amirthavalli V",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Amirthavalli_V_22x007.png",
  },
  {
    name: "Aniruth",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aniruth_22A205.png",
  },
  {
    name: "Aswin Balamuragan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aswin.png",
  },
  {
    name: "Likkeeth Kumar.S.B",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Likkeeth.png",
  },
  {
    name: "Prethvish Mo",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Prethvish.png",
  },
  {
    name: "Praveen Venkit P",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Praveen_Venkit.png",
  },
  {
    name: "Jeevan G K",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Jeevan.png",
  },
  {
    name: "Akash S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aakash.png",
  },
  {
    name: "Aakash M",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Aakash_20M601.png",
  },
  {
    name: "Kavya V.I",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Kavya_DESIGN.png",
  },
  {
    name: "Pradeep",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Pradeep.png",
  },
  {
    name: "Kavinkumar S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Kavin_21Y114.png",
  },
  {
    name: "Chandrakanth",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Chandrakanth_22N212.png",
  },
  {
    name: "Devanandh",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Devanandh_Y_22m607.png",
  },
  {
    name: "Eniyan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Eniyan_21s004.png",
  },
  {
    name: "Fasila Begum A",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Fasila_Begum_A_22d213.png",
  },
  {
    name: "Nandakishor G R",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/G.R.Nandakishor_22b211.png",
  },
  {
    name: "Giri Prassath S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Giri_Prassath_S_22z323.png",
  },
  {
    name: "Gokul",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Gokul.png",
  },
  {
    name: "Harisree",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Harisree.png",
  },
  {
    name: "Harrdik Krishna",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Harrdik_Krishna_22L163.png",
  },
  {
    name: "Harsha  Vardhana Ram A",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Harsha_Vardhana_Ram_A_22N220.png",
  },
  {
    name: "Jacin Wesly K",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Jacin_wesly_K_21E404.png",
  },
  {
    name: "Manoj Varun",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Manoj_varun.png",
  },
  {
    name: "Mugundan K",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Mugundan_K_22i236.png",
  },
  {
    name: "Naren Siddharth",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Naren_Siddharth_22z345.png",
  },
  {
    name: "Ohm Pranav",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Ohm_Pranav_22A230.png",
  },
  {
    name: "Pavithra",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Pavithra_22b230.png",
  },
  {
    name: "Purusoth Manak S",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Purusoth_manak_S_22L134.png",
  },
  {
    name: "Ramkumar",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Ramkumar_22m621.png",
  },
  {
    name: "Sandhiya",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Sandhiya_22z258.png",
  },
  {
    name: "Sasi Garan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/SasiGaran.png",
  },
  {
    name: "Thaarugeshwari KS",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Thaarugeshwari_KS_22i270.png",
  },
  {
    name: "Thiyagarajan",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Thiyagarajan.png",
  },
  {
    name: "Vijeyasri T",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Vijeyasri_T_22z272.png",
  },
  {
    name: "Vinaya Sri",
    vertical: "Design & Photography",
    position: "",
    image_url: "/assets/Team/Design/Vinaya_Sri_21b241.png",
  },
  {
    name: "Harsini S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/1harsini.png",
  },
  {
    name: "Harivardhan S V",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/2harivardhan.png",
  },
  {
    name: "Arun A R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/3arun.png",
  },
  {
    name: "Sreehari Krishnakumar",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/4sreehari.png",
  },
  {
    name: "Mohammed Rafi M",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/5rafi.png",
  },
  {
    name: "Sevathal S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/6sevathal.png",
  },
  {
    name: "Ellakiyaa A",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/7ellakiyaa.png",
  },
  {
    name: "Amrita B",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/8amrita.png",
  },
  {
    name: "Arunadithyan S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/9arunadithyan.png",
  },
  {
    name: "Harini Ragavi C",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/10harini.png",
  },
  {
    name: "Saipravin D",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/11saipravin.png",
  },
  {
    name: "K Aishvarya",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/12aishvarya.png",
  },
  {
    name: "Darsana R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/13darsana.png",
  },
  {
    name: "Harish Kumar R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/14harish.png",
  },
  {
    name: "Akshayaa",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/15akshayaa.png",
  },
  {
    name: "Sona B",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/16sona.png",
  },
  {
    name: "Abdeali Morudwala",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/17abdeali.png",
  },
  {
    name: "Nina Charles J",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/18nina.png",
  },
  {
    name: "Akshaya K",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/19akshaya.png",
  },
  {
    name: "Arunaa S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/20arunaa.png",
  },
  {
    name: "Ganesh Ram M",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/21ganesh.png",
  },
  {
    name: "M .Rajamanickam",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/22rajamanickam.png",
  },
  {
    name: "Selvakumar T",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/23selvakumar.png",
  },
  {
    name: "Kailash M B",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/24kailash.png",
  },
  {
    name: "Tharsha R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/25tharsha.png",
  },
  {
    name: "Mullainathan V H",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/26mullainathan.png",
  },
  {
    name: "Nithish Kumar N.R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/27nithish.png",
  },
  {
    name: "Thirugnana Sampathan S",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/29thiru.png",
  },
  {
    name: "Shri Nandhini A C ",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/30nandhini.png",
  },
  {
    name: "Sadhana J B",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/31sadhana.png",
  },
  {
    name: "Swathi",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/32swathi.png",
  },
  {
    name: "Shuki R",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/33shuki.png",
  },
  {
    name: "Rohit M",
    vertical: "Events Resource Management",
    position: "",
    image_url: "/assets/Team/Events/34rohit.png",
  },
  {
    name: "Dharmendra R",
    vertical: "Overall Coordinators",
    position: "Chairperson, Students Union",
    image_url: "/assets/Team/OBs/1dharmendra.jpeg",
  },
  {
    name: "Mano M",
    vertical: "Overall Coordinators",
    position: "Co-Chairperson, Students Union",
    image_url: "/assets/Team/OBs/2mano.jpeg",
  },
  {
    name: "Aditya Varma",
    vertical: "Overall Coordinators",
    position: "Secretary (Men), Students Union",
    image_url: "/assets/Team/OBs/3aditya.jpeg",
  },
  {
    name: "Sri Athrukshna B",
    vertical: "Overall Coordinators",
    position: "Secretary (Women), Students Union",
    image_url: "/assets/Team/OBs/4athrukshna.jpeg",
  },
  {
    name: "Pavana S",
    vertical: "Overall Coordinators",
    position: "Secretary (Science), Students Union",
    image_url: "/assets/Team/OBs/5pavana.jpeg",
  },
  {
    name: "Akshaiya",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Akshaiya_PR.png",
  },
  {
    name: "Raghan Harkesh R",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Raghan_Harkesh.png",
  },
  {
    name: "Deepti",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Deepti.png",
  },
  {
    name: "Manisha C",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Manisha_C_22d229.png",
  },
  {
    name: "Arunraja C",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Arun_Raja.png",
  },
  {
    name: "Lisalini.G",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Lisalini_21d218.png",
  },
  {
    name: "Sangamithra S",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Sangamithra.png",
  },
  {
    name: "Madumitha M P",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Madumitha_21c114.png",
  },
  {
    name: "Nakulan A",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Nakulan.png",
  },
  {
    name: "Reddy Jayakrishna",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Jayakrishana_Reddy.png",
  },
  {
    name: "Sreenitti S",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Srinithi.png",
  },
  {
    name: "Pramodini",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Pramodini_22z244.png",
  },
  {
    name: "Pranesh",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Pranesh_22m138.png",
  },
  {
    name: "Sakthi",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Sakthi_PR.png",
  },
  {
    name: "Sharmili",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Sharmili_G_22b240.png",
  },
  {
    name: "Swasthika",
    vertical: "PR and Sponsorship",
    position: "",
    image_url: "/assets/Team/PR/Swasthika_PR.png",
  },
];

export default TeamDetails;
